# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
{{- if .Values.edgex.storage.useHostPath }}
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-kuiper-data
spec:
  storageClassName: ""
  claimRef:
    name: kuiper-data
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 128Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-kuiper-data"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-kuiper-etc
spec:
  storageClassName: ""
  claimRef:
    name: kuiper-etc
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 8Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-kuiper-etc"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-kuiper-log
spec:
  storageClassName: ""
  claimRef:
    name: kuiper-log
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 128Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-kuiper-log"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-kuiper-plugins
spec:
  storageClassName: ""
  claimRef:
    name: kuiper-plugins
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 128Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-kuiper-plugins"
    type: DirectoryOrCreate
{{- end }}